---
title: "LilyChang_EDA"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(zipcodeR)
library(sf)
library(RColorBrewer)

```


```{r}
dataset <- read_csv("noise_complaints_cleaned.csv")
construction <- read_csv("new_homes_cleaned.csv")
alcohol <- read_csv("alcohol_licensing_cleaned.csv")

```
### EDA on the Noise Complaints dataset

```{r}
bargraph1 <- ggplot(dataset, aes(case_sub_type, fill = case_sub_type)) + geom_bar() +
  labs(
    title = "Counts for Reasoning behind Complaints",
    x = "case sub type"
  ) +
theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )
bargraph1
```

```{r}
count_by_category <- dataset |>
  count(case_year)

ggplot(count_by_category, aes(x = case_year, y = n, group = 1)) +
  geom_line() +
  labs(
    y = "Count",
    x = "Case Year",
    title = "Noise Complaints 1989-2026") +
  theme_stata()
```

```{r}
count_zip <- dataset |>
  select(zip_code) |>
  count(zip_code) |>
  arrange(desc(n))
count_zip
```

#### These bar graphs look at 2025 and 2018 specifically

Looking at the spike in 2025 and the years leading up to it
```{r}
filteredgraph25 <- dataset |>
  select(c("case_year", "case_sub_type", "zip_code")) |>
filter(case_year %in% c("2023","2024","2025"))
```

```{r}
filteredbar25 <- ggplot(filteredgraph25, aes(case_sub_type, fill=case_sub_type)) +
  geom_bar() +
  facet_wrap(~case_year) +
theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    ) + 
  labs(
    x = "Sub Type of the Complaint",
    title = "Counts for the case sub types from 2023 to 2025"
  )
filteredbar25
```

Looking at 2018 and the years before and after it
```{r}
filteredgraph18 <- dataset |>
  select(c("case_year", "case_sub_type", "zip_code")) |>
filter(case_year %in% c("2017","2018","2019", "2020", "2021"))
```

```{r}
filteredbar18 <- ggplot(filteredgraph18, aes(case_sub_type, fill=case_sub_type)) +
  geom_bar() +
  facet_wrap(~case_year) +
theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    ) + 
  labs(
    x = "Sub Type of the Complaint",
    title = "Counts for the case sub types from 2016 to 2020"
  )
filteredbar18
```

### Suface-level EDA on Construction and Alcohol Datasets

```{r}
count_by_categoryC <- construction |>
  count(year_of_issue)

linegraph_con <- ggplot(count_by_categoryC, aes(year_of_issue, n)) + geom_line() +
  theme_stata() +
  labs(
    title = "Licenses to build new homes from 1990 to 2026",
    x = "Year the license was issued",
    y = "counts"
  )
linegraph_con
```


Finding the city with the most stores licensed to sell alcohol
```{r}
most_concentrated <- alcohol |>
  count(zip) |>
  arrange(desc(n))

most_concentrated 
```


Looking at how different complaint causes behave over time.

```{r}
count_by_category_line <- dataset |>
  count(case_sub_type, case_year) |>
  filter(!case_sub_type %in% c("other_causes"))
count_by_category_line

ggplot(count_by_category_line, aes(x = case_year, y = n, color = case_sub_type, group = case_sub_type)) +
  geom_line(linewidth = 0.9) + 
scale_color_brewer(palette = "Set1") # + theme_dark()
#Set3, Paired
```





